tap "cloudflare/cloudflare"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "koekeishiya/formulae"
# Color-highlighted diff(1) output
brew "colordiff"
# General-purpose scripting language
brew "php"
# Dependency Manager for PHP
brew "composer"
# Command-line fuzzy finder written in Go
brew "fzf"
# Platform built on V8 to build network applications
brew "node"
# Shell command parallelization utility
brew "parallel"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# JavaScript package manager
brew "yarn"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Cloudflare Tunnel
brew "cloudflare/cloudflare/cloudflared", link: false
# Browser for SQLite databases
cask "db-browser-for-sqlite"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-monoid-nerd-font"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Toolbox companion for QMK Firmware
cask "qmk-toolbox"
# Open-source code editor
cask "visual-studio-code"
vscode "adrianwilczynski.alpine-js-intellisense"
vscode "ahmadalli.vscode-nginx-conf"
vscode "akamud.vscode-theme-onedark"
vscode "amiralizadeh9480.laravel-extra-intellisense"
vscode "austenc.laravel-blade-spacer"
vscode "bierner.emojisense"
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "cardinal90.multi-cursor-case-preserve"
vscode "cierra.livewire-vscode"
vscode "cjhowe7.laravel-blade"
vscode "codingyu.laravel-goto-view"
vscode "damms005.devdb"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "devsense.composer-php-vscode"
vscode "devsense.intelli-php-vscode"
vscode "devsense.phptools-vscode"
vscode "devsense.profiler-php-vscode"
vscode "drcika.apc-extension"
vscode "editorconfig.editorconfig"
vscode "entexa.tall-stack"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "fosshaas.fontsize-shortcuts"
vscode "glitchbl.laravel-create-view"
vscode "heybourn.headwind"
vscode "ihunte.laravel-blade-wrapper"
vscode "jaguadoromero.vscode-php-create-class"
vscode "lennardv.livewire-goto-updated"
vscode "loilo.snazzy-light"
vscode "mehedidracula.php-namespace-resolver"
vscode "mikestead.dotenv"
vscode "mohamedbenhida.laravel-intellisense"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "naoray.laravel-goto-components"
vscode "onecentlin.laravel-blade"
vscode "onecentlin.laravel-extension-pack"
vscode "onecentlin.laravel5-snippets"
vscode "patbenatar.advanced-new-file"
vscode "pgl.laravel-jump-controller"
vscode "pkief.material-icon-theme"
vscode "rangav.vscode-thunder-client"
vscode "rebornix.toggle"
vscode "reda-salmi.night-owl-x-one-dark"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "ryannaddy.laravel-artisan"
vscode "shalldie.background"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "shufo.vscode-blade-formatter"
vscode "sleistner.vscode-fileutils"
vscode "stevencl.adddoccomments"
vscode "stivo.tailwind-fold"
vscode "xdebug.php-debug"
